### ISSUE TITLE
Token Authentication

### ISSUE THREAD

**Issue by kmcgurie** [frumbert/moodle-token-enrolment#1]
Hello,

I have been attempting to use this plugin as a way to have employers issue tokens to their employees for self-registration onto our Moodle site.  The issue is that the confirmation email is never sent to the user whom consumed the token.  The email containing their username (email) and a uniquely generated password is sent and works; however, they are unable to enter the site as they have not confirmed their registration.  Additionally, when I attempt to manually confirm their enrollment through the user list page, I receive these errors:

Abstract user_confirm() method must be overridden.

More information about this error

×Debug info: 
Error code: mustbeoveride
×Stack trace:
line 495 of /lib/setuplib.php: moodle_exception thrown
line 350 of /lib/authlib.php: call to print_error()
line 59 of /admin/user.php: call to auth_plugin_base->user_confirm()

Any advice?

Thanks,
Kevin

**Comment by frumbert** [comment]
The `user_confirm` code is in the auth plugin now. Sorry about the time taken to get back to this one!

**Comment by kmcgurie** [comment]
Hello,

Thank you for the update;  however, I was able to figure out a workaround.  Thanks though!
